import { cp, mkdir, rm } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
await rm('dist', { recursive: true, force: true });
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
const local = 'node_modules/typescript/bin/tsc';
const command = existsSync(local) ? process.execPath : (process.platform === 'win32' ? 'tsc.cmd' : 'tsc');
const result = spawnSync(command, existsSync(local) ? [local] : [], { stdio: 'inherit', shell: process.platform === 'win32' && !existsSync(local) });
if (result.error) console.error('Install development tools with npm ci before building.', result.error.message);
process.exit(result.status ?? 1);
